### ISSUE TITLE
TypeError: Cannot read property 'actionName' of undefined  (via Account->Activity Panel -> Event drop down arrow button

### ISSUE THREAD

**Issue by petergascoyne** [SAItm/LWCActionContainer#4]
The action button not working via Activity Panel -> Event -> drop down arrow button:

![image](https://user-images.githubusercontent.com/917212/105364598-405ec580-5bf5-11eb-984f-58724f3b5ee5.png)

I can confirm that action button does however work via the header button on the record of the object the action is created on.

error message: 

LWCLightningAction.js:44 Uncaught (in promise) TypeError: Cannot read property 'actionName' of undefined
at eval (LWCLightningAction.js:44)
at s (aura_prod.js:37)

Error Line:
https://github.com/andrii-solokh/LWCAction/blob/e82ec6d07af5a225fb64af61d7451f51d14d6be6/force-app/main/default/aura/LWCLightningAction/LWCLightningActionHelper.js#L22

let me know if you have a fix and I'll do the same if identified.

Thanks,
Peter

**Comment by andrii-solokh** [comment]
Hello, 
Thank you for the report.

This implementation uses 'Quick Action API', we can get only selected action on record page, but not on activities tab.

Thanks,
Andrii
